# https://rust-lang.github.io/rustfmt/?version=v1.6.0
brace_style = "SameLineWhere"
comment_width = 120
control_brace_style = "AlwaysSameLine"
fn_params_layout = "Tall"
force_multiline_blocks = true
format_code_in_doc_comments = true
format_strings = true
group_imports = "StdExternalCrate"
hard_tabs = true
indent_style = "Block"
match_block_trailing_comma = true
max_width = 120
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
reorder_imports = true
reorder_modules = true
tab_spaces = 4
use_field_init_shorthand = false
use_small_heuristics = "Max"
use_try_shorthand = true
wrap_comments = true
